---
- name: Create CoreDNS systemd service file
  template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
  delegate_to: "{{ coredns_node }}"
  run_once: true
  tags: add_coredns

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: true
  delegate_to: "{{ coredns_node }}"
  run_once: true
  tags: add_coredns

- name: Enable and start CoreDNS service
  systemd:
    name: coredns
    enabled: yes
    state: started
  delegate_to: "{{ coredns_node }}"
  run_once: true
  tags: add_coredns
